### ISSUE TITLE
Implement rate-limiting of answer submissions

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#102]
Ideally, we want to be able to write a function `f` in the hunt configuration page so that, after the `n`-th incorrect answer submission for a particular puzzle in that hunt, the team will be locked out of submitting another answer for that puzzle for `f(n)` seconds.

**Comment by dlareau** [comment]
Do you have something special in mind that needs this framework? Ever since #55, teams have been ratelimited to 10 submissions per minute. Thanks to the plugin I'm using that would be really easy to allow for the hunt to specify some x and s such that a team is allowed no more than x submissions per s seconds. 

If you have some idea that really benefits from some custom backoff solution, the best improvement over the above that I could reasonably offer is that the admin would be able to specify a function that takes n and returns an (x,s) tuple that then gets plugged into the ratelimiting framework to say the user is ratelimited to x requests per s seconds. This is nearly the same, but slightly different in that the function returns a rate not a direct time.

**Comment by sam-yeom** [comment]
I didn't know that we currently had rate-limiting because we had teams spam answers despite what we already had. We definitely want to make it harder for teams to submit answers if they have a lot of incorrect submissions already.

I don't know about the specific implementation details of the existing rate-limiting. Would it be equivalent to what I originally asked for if we set x = 1? Are teams notified of the rate-limiting once they trigger it?

**Comment by dlareau** [comment]
Well, this is new...... I was ready to just be like "yeah, its on, and it shows the user a message when they've been limited".... except I just went to test it and it isn't working. It was definitely working at some point, I don't know when it broke. For now I'll mark this as a bug and then once I get the base implementation working again we can talk about improving it. 

As for the implementation details, I think x=1 might do what you want, not entirely sure yet. It would just be a matter of whether the value specified is the max allowed, or the point of limiting. (aka would x=1 limit the current request). The library in question is https://django-ratelimit.readthedocs.io/en/stable/index.html

**Comment by dlareau** [comment]
Okay, so ratelimiting was/is still on, but it would appear that because of the specific library implementation, the windowing is fixed and approximate, meaning setting a rate of x requests per s seconds could actually generate up to 2x requests per s seconds. (for example, if the rate is 10 requests per minute, the user could happen to submit 10 requests, then by pure luck roll over into a new time bin and then submit 10 more requests before being limited) In reality this ends up giving the user ~1.5x requests per s seconds if evenly spaced. This meant that in practice, during the last hunt, lucky users could have spammed up to 20 requests per minute which definitely seems like too much. 

This also throws some small (but not insurmountable) wrenches into the function based plan as the delays won't be exact. I'm gonna evaluate some options (including rolling our own solution) and see if any are easy.

For now, I learned that stacking limits is possible and it allows us to enforce both burst and long term limits. I'm going to start by changing the rates to a stacked group of:
2 request per 10 seconds (Stops burst guessing, but allows for typos)
5 requests per 60 seconds (stops many guesses in general)

If you have feedback about these rates I'd like to hear them. They could probably be even stricter, but now that so much about answer checking is automated I'm always in favor of leniency.

**Comment by dlareau** [comment]
rates updated in 07c60a7
I'm gonna leave this ticket open and we can see if we run into any issues in the upcoming hunt. Thanks to #83 we will have logs of any time a team gets ratelimited, so we can see how often it kicks in.

**Comment by dlareau** [comment]
@samuel-yeom @TomWildenhain Did there seem to be any issue with submission flooding? The logs seem to indicate that ratelimiting did kick in about a dozen times over the course of the hunt, the question is "was the bar set low enough?"

If it seemed fine, I think we can close this.

**Comment by sam-yeom** [comment]
No, I don't think the bar was set low enough. I've seen teams submit 20+ answers in 60 seconds. Is the rate-limiting on a per-client basis or a per-team basis?

**Comment by dlareau** [comment]
If we want to tighten down the limits more we can, but first I want to make sure we're both working off the same data. I think when the queue is scrolling by, it can feel like a lot of submissions are coming in.

I've just ran some analysis over the 5182 submissions that occurred during the 450 minutes the hunt was open for submissions. The ratelimiting is currently in place for users, but despite that, even when analyzed at the team level, no team submitted more than 20 submissions in 60 seconds. In fact, there were only 2 incidents of teams submitting more than 20 submissions in 120 seconds (not counting the last 6 minutes of the hunt where basically everybody spammed):
- ARCCvengers @ 4:20PM - 4:22PM - 28 submissions
- Fruzzle Front @ 7:44 PM - 7:46PM - 26 submissions

Here are some possible ways to work from this data:
- Change the ratelimiting to 5 submissions per minute per TEAM rather than per USER. This would certainly limit some of these more extreme cases, but would mean that every user on a team will get punished for their teammate spamming, but thats probably fine.
- Tighten down the per-user limitations even more, making it something like 3 submissions per user per minute, meaning that a team of 6 would be artificially limited to 18 submissions per minute even if every member was spamming. 
- Re-evaluate why it felt like there were 20+ submissions in 60 seconds when there weren't. Maybe we can make the queue page more intuitively split by team or by puzzle or something so it feels like submissions aren't flying by. Maybe we can implement some automatic visual grouping for teams that submit multiple incorrect answers in a row.

I'm open to thoughts on this. Attached is the summary doc used to get these numbers (requires excel because pivot tables)
[submissions.xlsx](https://github.com/dlareau/puzzlehunt_server/files/3703197/submissions.xlsx)

**Comment by pitrack** [comment]
Chiming in as a third-party observer: thanks for crunching the numbers and performing interesting analysis!

- Per team ratelimiting makes a lot more sense to me than per user, for several reasons (different team sizes, only one or two team members are submitting for their team because some people are solving on paper, encourages more team decisions).
- I really like your last point of re-evaluating the queue page (which is great as a log of submissions, but perhaps not the most visually useful). I encourage hunt staff to think about this more (than modifying parameters for rate limiting), especially as the hunt will continue to grow.

**Comment by dlareau** [comment]
Yeah, the page layout and general function hasn't changed (except for pagination) from the days where we would get roughly a few hundred submissions for the entire hunt and had to respond to each of them manually.

**Comment by timparenti** [comment]
Another outside perspective, but perhaps a tiered approach would be useful?  For example:
* 2 requests per user per 10 seconds (as before, to allow typos but stop bursts)
* N requests per TEAM per 60 seconds (to stop a whole team spamming over time and ensuring general team-to-team fairness)

As for the actual value of N, definitely evaluate key times when the sense of overwhelm manifested. 
Seems from discussion that a good N might be between 5 and 10, though tweaks to the queue UI to mitigate that overwhelm could allow N to be more permissive.

**Comment by dlareau** [comment]
As noted above, we're down much lower now, 2 per 10 seconds per user and 5 per 60 seconds for teams. As always, we'll see how this goes. I'm not closing the issue yet, but I am removing it from the v4 milestone.

**Comment by dlareau** [comment]
Any comments from the current hunt @samuel-yeom? The limits were as specified above on Feb 5. I'm interested in hearing how things were with a hunt of this scale.

**Comment by sam-yeom** [comment]
We think the rate-limiting worked well this time, and the parameters specified on Feb 5 seem about right. I'm closing this issue.
