### ISSUE TITLE
Bugs with staff hint display

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#130]
1. It seems that, when a hint request is close to spilling over to a new page due to incoming hint requests, the hint response box disappears and any stuff that we typed into the box is lost. I'm not sure what the best solution to this issue is, but it's very frustrating to lose what we typed into the box.
2. Filtering hints team/puzzle/status filters existing hints but not incoming ones.
3. When I refresh the page, sometimes the hint response that I submitted for a previous hint request appears in the hint response box for a different hint.

**Comment by dlareau** [comment]
1) Hmmmm, there are a few possible solutions to this:
- Stop polling for new hints while the text cursor is in a response box, this has the downside of someone possibly accidentally leaving their cursor in a text box and never getting updates
- Break out responding to a hint into a pop-up box/modal. The downside of this is that it takes up the screen (idk if y'all look at previous hints when typing the current one) and that it may feel clunkier in general than an inline response.
- Have the pagination code only push answered hints off the screen. The downside here is that if you walk away for a while the page could get pretty long.

Chat with staff and let me know which of the above (or some new thing entirely) sounds best.

2) Yeah, noticed that too late, already on a mental list, now it is on this actual list right here.

3) Weird, I'll look into that, some more exacting details wouldn't hurt.

**Comment by dlareau** [comment]
All three issues have been addressed.
1) I went with option 2 because it only had a possible UI downside instead of the other two which had a possible functionality downside. Responding to or editing the hint will now pop up a box to edit the response in, and while the original hint may scroll off the screen in the background, the box will stay up with all the relevant information.
2) The page will now only get updates for the current filter selection
3) I realized when the page is rendered it has the chance to prefill the form with the last submitted hint text. This has been fixed.
