### ISSUE TITLE
Canned response by default

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#32]
Can you add a toggle that enabled "Auto canned-response mode" so that we don't have to click "canned response" every time?

Thanks!

**Comment by dlareau** [comment]
Can you think of times that you would want this off? With the way this issue is phrased I would see this being left on for the whole hunt, which would just be way easier to implement. If you want the ability to turn this off I will put that in, but I'd hate for me to spend extra time coding a synchronized toggle for this feature and it to never be turned off.

**Comment by TomWildenhain** [comment]
Talked to the rest of the group and they said it's fine to not have a toggle and just make it all automatic.  Thanks!
