### ISSUE TITLE
Ability to make "current hunt" link to prepuzzle before hunt begins.

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#84]
Since we now have native prepuzzle support (yay!) maybe the current hunt page should be able to link to a prepuzzle if the hunt is not yet released.  For admins and playtesters, it would still go to the usual hunt page.

**Comment by dlareau** [comment]
That should be easy enough.

**Comment by dlareau** [comment]
Fixed in 5b529f8. New behavior is 
- Do the obvious thing for hunts that are over or happening now
- If the user is a playtester or staff, give them the hunt page
- If it is the day of the hunt and it isn't a case above, redirect them to a page saying the hunt is locked and will unlock at the proper time. This is to avoid any confusion if people are sitting in the opening meeting and try to access the hunt only to get the prepuzzle.
- If it is not the day of the hunt and there is a prepuzzle, redirect them to the prepuzzle.
- If it is not the day of the hunt and there isn't a prepuzzle, redirect them to the "Hunt info" page.

Additionally if any non-staff user tries to access a prepuzzle that is not yet released, they get redirected to the hunt info page rather than an access error page.

If any of that seems wrong, comment so below.
