### ISSUE TITLE
Launch support for solutions and puzzle data for CS hunt (Feb 23)

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#86]
If possible, it would be great to have the custom data field and support for posting solutions before we run CS Hunt on Feb 23.  If not, no problem.  Just let me know if you think it is feasible.

**Comment by dlareau** [comment]
I'm glad you brought this up, because I was going to bring it up soon anyways. I was going to ask if you wanted them for CS hunt, but it appears that got answered. I don't really feel like calling the set of things that have been worked on so far a release, but I can just push them to production for now so you can use them. 
A recap:
#85 (Fixed nav bar collapsing)
#74 (Filter queue by team and/or puzzle)
#71 (Release puzzle solutions through the server)
#77 (Custom puzzle data field)

I'll see what progress I make on other things this weekend and then push the current changes live. This issue will be closed once I update the production server. Let me know if there is some reason that it would be better to do it earlier this weekend rather than later this weekend.

**Comment by dlareau** [comment]
Server has been updated. I think everything is fine, but let me know if there are any issues. For all I know I forgot to set some permissions somewhere.

**Comment by TomWildenhain** [comment]
Thanks so much!  I'll check it out.
