### ISSUE TITLE
Add team list to Hunt info page in order of registration

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#97]
For assigning rooms to teams

**Comment by dlareau** [comment]
Gonna probably roll this into some way to mass assign teams from the info page.

**Comment by dlareau** [comment]
I want your opinions on in-server room assignment. 
It seems like it would simplify things a lot for both users and staff if there was an easy built in way to assign rooms.

What would you want this to look like? 
- A text box next to each team's name on the info page and you type them in?
- One big text box on the info page and you enter the rooms in either comma or line delimited format and they just get assigned in order of signup?
- Same as above but instead of automatically assigning it populates some sort of draggable "word bank" of rules where you then drag a room to each team?

I'm really open to suggestions for how this should work and how it should look.

**Comment by TomWildenhain** [comment]
I think room assignment would be a great tool to have on the server.  The hunt info page is a good place for it.  I would sort all the teams by signup order on that page and then put a text box next to each team's name.  I also like the idea of having a "bulk import" box that takes line delimited entries and gives rooms to teams (who don't have a room) based on signup order.  We would include more desirable rooms near the top of the list so they are given to teams who signed up first.  Sign up time is the time that the first team member was added (the time that the team was created).  I don't think we need any other ordering rules.

Thanks!

**Comment by dlareau** [comment]
Added in d63e7f0

Teams in the "need a room" area are now displayed in order of registration, and rooms can be typed in next to each team's name for quick assignment. Bulk import seemed like a bit of a hassle for right now and can be made as a separate issue if really desired.
